routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/feed', 302);
Route::redirect('/home', '/feed', 302);

Auth::routes();

Route::get('/logout', [
    'uses' => 'Auth\LoginController@logout',
    'as' => 'logout'
]);

Route::get('/feed', [
    'uses' => 'FeedController@index',
    'as' => 'getFeed'
]);

Route::get('/feed/{filter}', [
    'uses' => 'FeedController@index',
    'as' => 'getFeed'
]);

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::view('/', 'admin.index')->name('admin.index');
    Route::get('/categories', 'FeedCategoryController@index')->name('admin.categories.index');
    Route::post('/categories/store', 'FeedCategoryController@store')->name('admin.categories.store');
    Route::view('/categories/create', 'admin.categories.createNewForm')->name('admin.categories.create');
    Route::view('/urls', 'admin.urls.index')->name('admin.urls.index');
    Route::resource('FeedUrl', 'FeedUrlController');
});

app/Admin.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Admin extends Authenticatable
{
    use Notifiable;

    protected $guard = 'admin';

        /**
         * The attributes that are mass assignable.
         *
         * @var array
         */
        protected $fillable = [
            'name', 'email', 'password',
        ];

        /**
         * The attributes that should be hidden for arrays.
         *
         * @var array
         */
        protected $hidden = [
            'password', 'remember_token',
        ];
}

app/Feed.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Feed extends Model
{
    protected $fillable = ['title', 'link', 'description', 'publish_date', 'url_id'];

    public function getFeedUrl()
    {
        return $this->belongsTo(FeedUrl::class, 'url_id', 'id');
    }
}

app/FeedCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FeedCategory extends Model
{
    protected $fillable = [
        'category_title'
    ];

    public function getFeedUrls()
    {
        return $this->hasMany(FeedUrl::class, 'category_id', 'id');
    }
}

app/FeedUrl.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FeedUrl extends Model
{
    protected $fillable = [
        'title', 'url', 'description', 'category_id'
    ];

    public function getCategory()
    {
        return $this->belongsTo(FeedCategory::class, 'category_id', 'id');
    }

    public function getFeeds()
    {
        return $this->hasMany(Feed::class, 'url_id', 'id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FeedCategoryController.php
<?php

namespace App\Http\Controllers;

use App\FeedCategory;
use App\Http\Requests\FeedCategoryRequest;
use App\Services\CreateCategoryService;
use Illuminate\Http\Response;
use Illuminate\View\View;

class FeedCategoryController extends Controller
{
    private $createCategoryService;
    private $categoriesObj;

    public function __construct(CreateCategoryService $createCategoryService, FeedCategory $feedCategory)
    {
        $this->createCategoryService = $createCategoryService;
        $this->categoriesObj = $feedCategory;
    }

    /**
     * Display index
     *
     * @return View
     */
    public function index(): View
    {
        $categories = $this->categoriesObj->all();
        return view('admin.categories.index', ['categories' => $categories]);
    }

    /**
     * Create new category
     *
     * @param FeedCategoryRequest $request
     *
     * @return Response
     */
    public function store(FeedCategoryRequest $request): Response
    {
        $this->createCategoryService->createCategory($request->all());
        return redirect()->route('admin.categories.index')->with('success', 'Successfully created category!');
    }
}

app/Http/Controllers/FeedController.php
<?php

namespace App\Http\Controllers;

use App\FeedCategory;
use App\FeedUrl;
use App\Services\GetFeedsFromDatabaseService;
use Illuminate\View\View;

class FeedController extends Controller
{
    private $getFeedsFromDatabaseService;
    private $feedCategoryObject;
    private $feedUrlsObject;

    public function __construct(
        GetFeedsFromDatabaseService $getFeedsFromDatabaseService,
        FeedCategory $feedCategoryObject,
        FeedUrl $feedUrlsObject
    )
    {
        $this->feedCategoryObject = $feedCategoryObject;
        $this->getFeedsFromDatabaseService = $getFeedsFromDatabaseService;
        $this->feedUrlsObject = $feedUrlsObject;
    }

    /**
     * Display a listing of the resource.
     *
     * @param string $filter
     *
     * @return View
     */
    public function index(string $filter = null): View
    {
        $filters = $this->feedCategoryObject->all();
        $feed = $this->getFeedsFromDatabaseService->getFeeds($filter);
        $feedProviders = $this->feedUrlsObject->all();

        return view('feed',
            [
                'feed' => $feed,
                'currentFilter' => $filter,
                'filters' => $filters,
                'feedProviders' => $feedProviders
            ]);
    }
}

app/Http/Controllers/FeedUrlController.php
<?php

namespace App\Http\Controllers;

use App\FeedCategory;
use App\Http\Requests\FeedUrlRequest;
use App\Repositories\UrlCRUD\EloquentUrlCRUD;
use Illuminate\Http\Response;
use Illuminate\View\View;

class FeedUrlController extends Controller
{
    private $urlCRUD;
    private $categoryObj;

    public function __construct(EloquentUrlCRUD $urlCRUD, FeedCategory $categoryObj)
    {
        $this->urlCRUD = $urlCRUD;
        $this->categoryObj = $categoryObj;
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $urls = $this->urlCRUD->getAll();
        return view('admin.urls.index', ['urls' => $urls]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        $categories = $this->categoryObj->all();
        return view('admin.urls.createNewUrlForm', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  FeedUrlRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(FeedUrlRequest $request): Response
    {
        $this->urlCRUD->store($request->all());
        return redirect()->route('FeedUrl.index')->with('success', 'Successfully created url!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return View
     */
    public function show(int $id): View
    {
        $url = $this->urlCRUD->getById($id);
        $category = $this->categoryObj->where('id', $url->category_id)->select('category_title')->first();
        $url->category_title = $category['category_title'];
        return view('admin.urls.showSingleItem', ['url' => $url]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return View
     */
    public function edit(int $id): View
    {
        $url = $this->urlCRUD->getById($id);
        $categories = $this->categoryObj->all();
        return view('admin.urls.editForm', ['url' => $url, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param FeedUrlRequest $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(FeedUrlRequest $request, int $id): Response
    {
        $this->urlCRUD->update($id, $request->all());
        return redirect()->route('FeedUrl.index')->with('success', 'Successfully updated url!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id): Response
    {
        $this->urlCRUD->destroy($id);
        return redirect()->route('FeedUrl.index')->with('success', 'Successfully deleted url!');
    }
}

resources/views/admin/categories/createNewForm.blade.php
@extends('layouts.master')

@section('title')
    Categories index
@endsection

@section('content')
    <div class="container">
        <h1>Categories</h1>
        @include('partials.sessionErrorSuccessMessages')
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default padding-20-bottom padding-20-top">
                    <a href="#" class="btn btn-outline-success">Create new</a>
                </div>
                <form action="{{route('admin.categories.store')}}" method="post">
                    <label for="category_title">Title</label>
                    <input type="text" name="category_title">
                    {{csrf_field()}}
                    <div class="row padding-20-top">
                        <div class="col-md-8 col-md-offset-2">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.master')

@section('title')
    Categories index
@endsection

@section('content')
    <div class="container">
        <h1>Categories</h1>
        @include('partials.sessionErrorSuccessMessages')
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default padding-20-bottom padding-20-top">
                    <a href="{{route('admin.categories.create')}}" class="btn btn-outline-success">Create new</a>
                </div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Cat. Id</th>
                        <th scope="col">Title</th>
                    </tr>
                    </thead>
                    @foreach($categories as $category)
                        <tbody>
                        <tr>
                            <th scope="row">{{$loop->iteration}}</th>
                            <td>{{$category->id}}</td>
                            <td>{{$category->category_title}}</td>
                        </tr>
                        </tbody>
                    @endforeach
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.master')

@section('title')
    Admin index
@endsection

@section('content')
    <div class="container">
        <h1>Admin index page</h1>
        <h2>You are logged in as <strong>{{Auth::user()->email}}</strong></h2>
        @include('partials.sessionErrorSuccessMessages')
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <a href="{{route('admin.categories.index')}}" class="btn btn-outline-primary"
                       onclick="">Categories</a>
                    <a href="{{route('FeedUrl.index')}}" class="btn btn-outline-success" onclick="">Urls</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/urls/createNewUrlForm.blade.php
@extends('layouts.master')

@section('title')
    Create category
@endsection

@section('content')
    <div class="container">
        <h1>Create new url</h1>
        <div class="row">
            <div class="col-lg-12">
                <form action="{{route('FeedUrl.store')}}" method="post">
                    <div class="form-control">
                        <label for="title"><strong>Url title</strong></label>
                        <br>
                        <input type="text" placeholder="Title" name="title">
                        <br>

                        <label for="url"><strong>Url</strong></label>
                        <br>
                        <input type="text" placeholder="http://www.example.com/ex" name="url">

                        <label for="description"><strong>Description</strong></label>
                        <br>
                        <input type="text" placeholder="Description" name="description">

                        <label for="category_id"><strong>Description</strong></label>
                        <br>

                        <select name="category_id">
                            <option value="-1">Choose</option>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}">{{$category->category_title}}</option>
                            @endforeach

                            {{csrf_field()}}
                            <div class="row padding-20-top">
                                <div class="col-lg-12">
                                    <button type="submit" class="btn btn-success ">Submit</button>
                                    <a href="{{route('FeedUrl.index')}}" class="btn btn-primary">Go
                                        back</a>
                                </div>
                            </div>
                        </select>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/urls/editForm.blade.php
@extends('layouts.master')

@section('title')
    Edit url
@endsection

@section('content')
    <div class="container">
        <h1>Update existing url</h1>
        <div class="row">
            <div class="col-lg-12">
                <form action="{{route('FeedUrl.update',['id' => $url->id])}}" method="post">
                    <div class="form-control">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">

                        <label for="title"><strong>Url title</strong></label>
                        <br>
                        <input type="text" value="{{$url->title}}" placeholder="{{$url->title}}" name="title">
                        <br>

                        <label for="url"><strong>Url</strong></label>
                        <br>
                        <input type="text" value="{{$url->url}}" placeholder="{{$url->url}}" name="url">

                        <label for="description"><strong>Description</strong></label>
                        <br>
                        <input type="text" value="{{$url->description}}" placeholder="{{$url->description}}"
                               name="description">

                        <label for="category_id"><strong>Description</strong></label>
                        <br>

                        <select name="category_id">
                            <option value="-1">Choose</option>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}">{{$category->category_title}}</option>
                            @endforeach

                            {{csrf_field()}}
                            <div class="row padding-20-top">
                                <div class="col-lg-12">
                                    <button type="submit" class="btn btn-success ">Submit</button>
                                    <a href="{{route('FeedUrl.show',['id' => $url->id])}}" class="btn btn-primary">Go
                                        back</a>
                                </div>
                            </div>
                        </select>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/urls/index.blade.php
@extends('layouts.master')

@section('title')
    Url feed CRUD index
@endsection

@section('content')
    <div class="container">
        <h1>Url CRUD page</h1>
        @include('partials.sessionErrorSuccessMessages')
        <div class="row">
            <div class="col-md-12 col-md-offset-2 padding-20-top">
                <a href="{{route('FeedUrl.create')}}" class="btn btn-outline-success">Create new</a>
                <div class="panel panel-default padding-20-top">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Id</th>
                            <th scope="col">Url</th>
                            <th scope="col">Title</th>
                            <th scope="col">Category</th>
                            <th scope="col">Show</th>
                        </tr>
                        </thead>
                        @foreach($urls as $url)
                            <tbody>
                            <tr>
                                <th scope="row">{{$loop->iteration}}</th>
                                <td>{{$url->id}}</td>
                                <td>{{$url->url}}</td>
                                <td>{{$url->title}}</td>
                                <td>{{$url->getCategory['category_title']}}</td>
                                <td>
                                    <a href="{{route('FeedUrl.show',['id' => $url->id])}}"
                                       class="btn btn-primary">
                                        Show
                                    </a>
                                </td>
                            </tr>
                            </tbody>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/urls/showSingleItem.blade.php
@extends('layouts.master')

@section('title')
    Url
@endsection

@section('content')
    <div class="container">
        <h1>Url</h1>
        <h2>Title: {{$url->title}}</h2>
        <h3>Url id: <strong>{{$url->id}}</strong>, {{$url->url}}</h3>
        <p>Category title (id: <strong>{{$url->category_id}}</strong>): {{$url->category_title}}</p>
        <div class="row">
            <div class="col-md-4 col-md-offset-2 padding-20-top">
                <div class="row">
                    <a href="{{route('FeedUrl.edit',['id' => $url->id])}}" class="btn btn-primary">
                        Edit
                    </a>
                    <form action="{{route('FeedUrl.destroy',['id' => $url->id])}}" method="POST"
                          class="padding-20-left">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        {{csrf_field()}}
                        <button class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/feed.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <h1>Welcome to RSS feed!</h1>
        <div class="row">
            <div class="col-lg-3">
                <h5 class="padding-20-top">Providers list</h5>
                @foreach($feedProviders as $provider)
                    <div class="row">
                        <a href="{{$provider->url}}" target="_blank">&#8226 {{$provider->title}}</a>
                    </div>
                @endforeach
            </div>
            <div class="col-lg-8 col-lg-offset-3 padding-20-top">
                <form id="dropdown" onchange="handleSelect()">
                    <label for="filter">Filter</label>
                    <select name="filter">
                        <option value="Choose">Choose</option>
                        <option value="All">All</option>
                        @foreach($filters as $filter)
                            <option value="{{$filter->category_title}}">{{$filter->category_title}}</option>
                        @endforeach
                    </select>
                </form>
                <p class="padding-20-left">Current filter: <strong>{{$currentFilter}}</strong></p>
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <hr class="max-length">
                        @foreach($feed as $f)
                            @include('partials.modal')
                            <a href="#" data-toggle="modal" data-target="#product_view{{$f['id']}}"><h5
                                        class="text-center">{{$f['title']}}</h5></a>
                            <hr class="max-length">
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

@section('scripts')
    <script type="text/javascript">
        function handleSelect() {
            var option = $('#dropdown').find(":selected").text();
            window.location.href = '{{URL::to('/feed')}}/' + option;
        }
    </script>
@endsection

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
          integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link rel="stylesheet" href="{{URL::to('css/master.css')}}">
    @yield('styles')
</head>
<body>
@include('partials.header')
{{--fixes header--}}
<div class="padding-80-top"></div>
@yield('content')

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
        integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>
@yield('scripts')
</body>
</html>

resources/views/partials/header.blade.php
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{{route('getFeed','')}}">RSS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarHeaderShop">
        <ul class="navbar-nav">
            @auth()
                <a class="nav-link" href="{{route('logout')}}"><i class="fa fa-user" aria-hidden="true"></i> Logout</a>
                <a class="nav-link" href="{{route('admin.index')}}"><i class="fa fa-user"
                                                                       aria-hidden="true"></i>Admin Index</a>
            @else
                <li class="nav-item">
                    <a class="nav-link" href="{{route('login')}}"><i class="fa fa-user" aria-hidden="true"></i>
                        Login</a>
                </li>
            @endauth
        </ul>
    </div>
</nav>

resources/views/partials/modal.blade.php
<div class="modal fade product_view" id="product_view{{$f['id']}}">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                <h3 class="modal-title">{{$f['title']}}</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <p>{!! $f['description'] !!}</p>
                    </div>
                    <div class="col-md-6 col-md-offset-2">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <a href="{{$f['link']}}" class="btn btn-outline-primary" target="_blank">See more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/partials/sessionErrorSuccessMessages.blade.php
<div class="alert alert-danger center-block offset" {{!Session::has('error') ? 'hidden' : ''}}>
    {{Session::get('error')}}
</div>
<div class="alert alert-success center-block offset"{{!Session::has('success') ? 'hidden' : ''}}>
    {{Session::get('success')}}
</div>